version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata
#    env_file:
#      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastpass
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
#    env_file:
#      - .env
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=postgres@fastpass.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:5050


  fastpass:
    #image: python:3.8
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastpass
    volumes:
      - ./backend:/app
    ports:
    - 8000:8000
    depends_on:
      - postgres
    links:
      - postgres:postgres
