"""empty message

Revision ID: 27c34495d970
Revises: d68d5b519e6d
Create Date: 2020-07-14 16:38:37.944701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c34495d970'
down_revision = 'd68d5b519e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_labels_description', table_name='labels')
    op.drop_index('ix_labels_name', table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_labels_name', 'labels', ['name'], unique=False)
    op.create_index('ix_labels_description', 'labels', ['description'], unique=False)
    # ### end Alembic commands ###
