"""empty message

Revision ID: 7de38cf8e18d
Revises: 507a7e92e461
Create Date: 2020-07-14 19:54:27.980257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de38cf8e18d'
down_revision = '507a7e92e461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
