"""empty message

Revision ID: 844ebd354238
Revises: 27c34495d970
Create Date: 2020-07-14 16:42:39.350939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844ebd354238'
down_revision = '27c34495d970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
