"""empty message

Revision ID: 89526450d778
Revises: 7de38cf8e18d
Create Date: 2020-07-17 18:21:25.308869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89526450d778'
down_revision = '7de38cf8e18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
